"C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI\Scripts\Initialize-PowerCLIEnvironment.ps1\"
Import-Module VMware.VimAutomation.Cis.Core

$Creds = Get-Credential
$FlashArray = New-PfaArray -EndPoint '<IP/DNS>' -Credentials $Creds -IgnoreCertificateError

$ESXHosts = @('B200M4-01','B200M4-02','B200M4-03','B200M4-04',`
              'B200M4-05','B200M4-06','B200M4-07','B200M4-08')
$ExVolNamePrefix = 'EX'

For($i=2;$i -le 24; $i++)
{
    For($z=2; $z -le 7; $z++)
    {
        For($x=1; $x -le 4; $x++) 
        {
            New-PfaVolume -Array $FlashArray -VolumeName "$ExVolName-$i-DB$x" -Size 2 -Unit TB 
            New-PfaVolume -Array $FlashArray -VolumeName "$ExVolName-$i-LOG$x" -Size 200 -Unit GB
            
            New-PfaHostVolumeConnection -Array $FlashArray `
                -VolumeName "$ExVolName-$i-DB$x" -HostName $ESXHosts[$z]
            New-PfaHostVolumeConnection -Array $FlashArray `
                -VolumeName "$ExVolName-$i-LOG$x" -HostName $ESXHosts[$z]
        }
    }
}

$vCenterIP = '<IP/DNS>'
$vCenterCluster = '<CLUSTERNAME>'
$vCenterAdmin = '<VCENTERADMIN>'
$Pwd = ConvertTo-SecureString 'MyEasyPassword' -AsPlainText -Force
$Creds = New-Object System.Management.Automation.PSCredential ($vCenterAdmin, $pwd)

Connect-VIServer -Server $vCenterIP -Credential $Creds 
Get-Cluster $vCenterCluster | Get-VMHost | Get-VMHostStorage -RescanAllHba -RescanVmfs | Out-Null
Get-ScsiLun -VmHost (Get-VMHost) | Where-Object { $_.CanonicalName -like 'naa.624*' } | Select-Object CanonicalName

# SIG # Begin signature block
# MIITTgYJKoZIhvcNAQcCoIITPzCCEzsCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUTraWAArIPnt76DR6bkVvJAS/
# 8BCggg3qMIIEFDCCAvygAwIBAgILBAAAAAABL07hUtcwDQYJKoZIhvcNAQEFBQAw
# VzELMAkGA1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNV
# BAsTB1Jvb3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw0xMTA0
# MTMxMDAwMDBaFw0yODAxMjgxMjAwMDBaMFIxCzAJBgNVBAYTAkJFMRkwFwYDVQQK
# ExBHbG9iYWxTaWduIG52LXNhMSgwJgYDVQQDEx9HbG9iYWxTaWduIFRpbWVzdGFt
# cGluZyBDQSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlO9l
# +LVXn6BTDTQG6wkft0cYasvwW+T/J6U00feJGr+esc0SQW5m1IGghYtkWkYvmaCN
# d7HivFzdItdqZ9C76Mp03otPDbBS5ZBb60cO8eefnAuQZT4XljBFcm05oRc2yrmg
# jBtPCBn2gTGtYRakYua0QJ7D/PuV9vu1LpWBmODvxevYAll4d/eq41JrUJEpxfz3
# zZNl0mBhIvIG+zLdFlH6Dv2KMPAXCae78wSuq5DnbN96qfTvxGInX2+ZbTh0qhGL
# 2t/HFEzphbLswn1KJo/nVrqm4M+SU4B09APsaLJgvIQgAIMboe60dAXBKY5i0Eex
# +vBTzBj5Ljv5cH60JQIDAQABo4HlMIHiMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMB
# Af8ECDAGAQH/AgEAMB0GA1UdDgQWBBRG2D7/3OO+/4Pm9IWbsN1q1hSpwTBHBgNV
# HSAEQDA+MDwGBFUdIAAwNDAyBggrBgEFBQcCARYmaHR0cHM6Ly93d3cuZ2xvYmFs
# c2lnbi5jb20vcmVwb3NpdG9yeS8wMwYDVR0fBCwwKjAooCagJIYiaHR0cDovL2Ny
# bC5nbG9iYWxzaWduLm5ldC9yb290LmNybDAfBgNVHSMEGDAWgBRge2YaRQ2XyolQ
# L30EzTSo//z9SzANBgkqhkiG9w0BAQUFAAOCAQEATl5WkB5GtNlJMfO7FzkoG8IW
# 3f1B3AkFBJtvsqKa1pkuQJkAVbXqP6UgdtOGNNQXzFU6x4Lu76i6vNgGnxVQ380W
# e1I6AtcZGv2v8Hhc4EvFGN86JB7arLipWAQCBzDbsBJe/jG+8ARI9PBw+DpeVoPP
# PfsNvPTF7ZedudTbpSeE4zibi6c1hkQgpDttpGoLoYP9KOva7yj2zIhd+wo7AKvg
# IeviLzVsD440RZfroveZMzV+y5qKu0VN5z+fwtmK+mWybsd+Zf/okuEsMaL3sCc2
# SI8mbzvuTXYfecPlf5Y1vC0OzAGwjn//UYCAp5LUs0RGZIyHTxZjBzFLY7Df8zCC
# BJ8wggOHoAMCAQICEhEh1pmnZJc+8fhCfukZzFNBFDANBgkqhkiG9w0BAQUFADBS
# MQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEoMCYGA1UE
# AxMfR2xvYmFsU2lnbiBUaW1lc3RhbXBpbmcgQ0EgLSBHMjAeFw0xNjA1MjQwMDAw
# MDBaFw0yNzA2MjQwMDAwMDBaMGAxCzAJBgNVBAYTAlNHMR8wHQYDVQQKExZHTU8g
# R2xvYmFsU2lnbiBQdGUgTHRkMTAwLgYDVQQDEydHbG9iYWxTaWduIFRTQSBmb3Ig
# TVMgQXV0aGVudGljb2RlIC0gRzIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
# AoIBAQCwF66i07YEMFYeWA+x7VWk1lTL2PZzOuxdXqsl/Tal+oTDYUDFRrVZUjtC
# oi5fE2IQqVvmc9aSJbF9I+MGs4c6DkPw1wCJU6IRMVIobl1AcjzyCXenSZKX1GyQ
# oHan/bjcs53yB2AsT1iYAGvTFVTg+t3/gCxfGKaY/9Sr7KFFWbIub2Jd4NkZrItX
# nKgmK9kXpRDSRwgacCwzi39ogCq1oV1r3Y0CAikDqnw3u7spTj1Tk7Om+o/SWJMV
# TLktq4CjoyX7r/cIZLB6RA9cENdfYTeqTmvT0lMlnYJz+iz5crCpGTkqUPqp0Dw6
# yuhb7/VfUfT5CtmXNd5qheYjBEKvAgMBAAGjggFfMIIBWzAOBgNVHQ8BAf8EBAMC
# B4AwTAYDVR0gBEUwQzBBBgkrBgEEAaAyAR4wNDAyBggrBgEFBQcCARYmaHR0cHM6
# Ly93d3cuZ2xvYmFsc2lnbi5jb20vcmVwb3NpdG9yeS8wCQYDVR0TBAIwADAWBgNV
# HSUBAf8EDDAKBggrBgEFBQcDCDBCBgNVHR8EOzA5MDegNaAzhjFodHRwOi8vY3Js
# Lmdsb2JhbHNpZ24uY29tL2dzL2dzdGltZXN0YW1waW5nZzIuY3JsMFQGCCsGAQUF
# BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3NlY3VyZS5nbG9iYWxzaWduLmNv
# bS9jYWNlcnQvZ3N0aW1lc3RhbXBpbmdnMi5jcnQwHQYDVR0OBBYEFNSihEo4Whh/
# uk8wUL2d1XqH1gn3MB8GA1UdIwQYMBaAFEbYPv/c477/g+b0hZuw3WrWFKnBMA0G
# CSqGSIb3DQEBBQUAA4IBAQCPqRqRbQSmNyAOg5beI9Nrbh9u3WQ9aCEitfhHNmmO
# 4aVFxySiIrcpCcxUWq7GvM1jjrM9UEjltMyuzZKNniiLE0oRqr2j79OyNvy0oXK/
# bZdjeYxEvHAvfvO83YJTqxr26/ocl7y2N5ykHDC8q7wtRzbfkiAD6HHGWPZ1BZo0
# 8AtZWoJENKqA5C+E9kddlsm2ysqdt6a65FDT1De4uiAO0NOSKlvEWbuhbds8zkSd
# wTgqreONvc0JdxoQvmcKAjZkiLmzGybu555gxEaovGEzbM9OuZy5avCfN/61PU+a
# 003/3iCOTpem/Z8JvE3KGHbJsE2FUPKA0h0G9VgEB7EYMIIFKzCCBBOgAwIBAgIQ
# CamgNd9B0v6RJ4iA0KHDFDANBgkqhkiG9w0BAQsFADByMQswCQYDVQQGEwJVUzEV
# MBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29t
# MTEwLwYDVQQDEyhEaWdpQ2VydCBTSEEyIEFzc3VyZWQgSUQgQ29kZSBTaWduaW5n
# IENBMB4XDTE2MDQyMzAwMDAwMFoXDTE3MDQyNzEyMDAwMFowaDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFDASBgNVBAcTC1NhbnRhIENsYXJhMRYw
# FAYDVQQKEw1Sb2JlcnQgQmFya2VyMRYwFAYDVQQDEw1Sb2JlcnQgQmFya2VyMIIB
# IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr1I0EO2uOScoPi9giUITw4CH
# 1qT2MJsPqG4pHhndW2M12EBl4HcDVi/cOZG+EZHduaKFSXy6nR0BuPbNB76/NODd
# S0id2Q7ppWbtld74O/OmtLn6SAW6qjKeYas7N4xUV6pK62yzGGBG/gr9CS97kzaW
# 6mwR803MmTwTVa9QofV3DioppJM7eTWSmPHUfyGVAE1LjnlYlgKPcAGGmtseXKwQ
# jyXq8wCvlnUOPiHZp/cXPpJzYq6krehZnnEqNLALQROtBEqnKXGFEQH8U0Qc7pqu
# gO+0lhnbV9/XLwIauyjLqNyJ+p7lZ8ZElS17j9PjQuJ+hyXotzPL1WIod9ghXwID
# AQABo4IBxTCCAcEwHwYDVR0jBBgwFoAUWsS5eyoKo6XqcQPAYPkt9mV1DlgwHQYD
# VR0OBBYEFJQeLmdYk4a/RXLk2t9XUgabNd/RMA4GA1UdDwEB/wQEAwIHgDATBgNV
# HSUEDDAKBggrBgEFBQcDAzB3BgNVHR8EcDBuMDWgM6Axhi9odHRwOi8vY3JsMy5k
# aWdpY2VydC5jb20vc2hhMi1hc3N1cmVkLWNzLWcxLmNybDA1oDOgMYYvaHR0cDov
# L2NybDQuZGlnaWNlcnQuY29tL3NoYTItYXNzdXJlZC1jcy1nMS5jcmwwTAYDVR0g
# BEUwQzA3BglghkgBhv1sAwEwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGln
# aWNlcnQuY29tL0NQUzAIBgZngQwBBAEwgYQGCCsGAQUFBwEBBHgwdjAkBggrBgEF
# BQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tME4GCCsGAQUFBzAChkJodHRw
# Oi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRTSEEyQXNzdXJlZElEQ29k
# ZVNpZ25pbmdDQS5jcnQwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEA
# K7mB6k0XrieW8Fgc1PE8QmQWhXieDu1TKWAltSgXopddqUyLCdeqMoPj6otYYdnL
# Nf9VGjxCWnZj1qXBrgyYv1FuWgwDhfL/xmZ09uKx9yIjx45HFU1Pw3sQSQHO+Q0p
# p652T7V7pfs9wcsqzUZJpdCRXtWAPpGuYyW+oX3jai6Mco/DrdP6G7WPMnlc/5yV
# 7Y824yXsJKoX/qENgtbctZeQ4htx4aaT3Pg79ppUunl754w8MDAVTQUVrKGH3TDw
# sBTRjsGb7on+QldBJzOsrE2Pq9P4fnIYdqO74JQ5YpUHn2p1pLXSukWchNgIeix/
# yCdjn78jL/RvpsJoSPdKfzGCBM4wggTKAgEBMIGGMHIxCzAJBgNVBAYTAlVTMRUw
# EwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20x
# MTAvBgNVBAMTKERpZ2lDZXJ0IFNIQTIgQXNzdXJlZCBJRCBDb2RlIFNpZ25pbmcg
# Q0ECEAmpoDXfQdL+kSeIgNChwxQwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwx
# CjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGC
# NwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFN29Y9+r7j3J1qOk
# Mt8z6XNg809jMA0GCSqGSIb3DQEBAQUABIIBAE+cpppXypuGlZ05nK3txGGo1/2U
# k+9NveTvY44TKSQN2srSATn4u79zqSlRH9SEdJhxH5SmBpMCaGngurRN4hxjWFDW
# kAxTxvyBB2AjZ4tLyK21/A3GkCxlWwY4f/UKSnDVJOzCZzcmqyF48nJTY/RlPvju
# MJyhHtiMvhTOuHWDcCCNANW4gZ7SJbDogK+cZCaz6J8mCzCEWU5jqFZ9qU4nBk9p
# OaUw7uOaSCvowzdIe/rLPC3tqMm1luE7EuhtyYM8TX9UxvAHhm9M88OrG7zU4xoF
# I+JS1ioNjHr7D9ea5Um7Bu6P/rCFXvuEzwJk/ZPfeqBqNg2jSi/8ejfG116hggKi
# MIICngYJKoZIhvcNAQkGMYICjzCCAosCAQEwaDBSMQswCQYDVQQGEwJCRTEZMBcG
# A1UEChMQR2xvYmFsU2lnbiBudi1zYTEoMCYGA1UEAxMfR2xvYmFsU2lnbiBUaW1l
# c3RhbXBpbmcgQ0EgLSBHMgISESHWmadklz7x+EJ+6RnMU0EUMAkGBSsOAwIaBQCg
# gf0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTYw
# NjExMTcxNTUzWjAjBgkqhkiG9w0BCQQxFgQU2BkmnjrhcSZF+nPt8xzUcegwuCsw
# gZ0GCyqGSIb3DQEJEAIMMYGNMIGKMIGHMIGEBBRjuC+rYfWDkJaVBQsAJJxQKTPs
# eTBsMFakVDBSMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1z
# YTEoMCYGA1UEAxMfR2xvYmFsU2lnbiBUaW1lc3RhbXBpbmcgQ0EgLSBHMgISESHW
# madklz7x+EJ+6RnMU0EUMA0GCSqGSIb3DQEBAQUABIIBAKNW+I/zGKl7aK4geWoc
# rMzFAWFsBFeozyYdXOBn3kICKpAMh0v7KEiLHYZxa3vwGRJRZvd+Jtfs7kjxyMcJ
# y3I3Ba32OBWexcQXq9Ml10V7+0WhvItvL7Wbe1D3SgMnzyhdGeZgVct/oKVJkIa6
# fTLzLQ9TrK3XP9b+sES8vOrpbbxNU7IJ6EwP4YEp/JkbyvqzPn1Otl2ncmgc0ssc
# MhaG/U8qwZGd6v7N4RO9TBJk1rHugdSLl3xOzA4ChcJSQfWSXRESwEB+kqsoYkZS
# RkHZDge1DF4UAreuBKPdlxaRexB054pw///osA0RvqA9d2eKEgQXrPw60pOiW+L3
# +os=
# SIG # End signature block
